### PR TITLE
Add voicebase dual channel audio analysis Skill sample

### PR DESCRIPTION
**Pull request by jcleblanc**
This is a first commit of the VoiceBase dual channel audio analysis skill, which uses AWS lambda as the serverless middleware layer.

### CODE REVIEW

**Comment by cbetta** [comment]
@jcleblanc thanks for adding this Skill. We'd like to bring all Skills in line with eachother so please can you:

- [ ] Please bring your README in line with [the README for the Rossum Skill](https://github.com/box-community/sample-document-skills/blob/master/rossum-invoice-intelligence/README.md) 
- [ ] Ensure your skill works with serverless on AWS
- [ ] Send me a screenshot, or share some files with me so I can edit that into a nicer screenshot?
- [ ] @eshaverma can you give the code a review and approve this PR?

**Comment by jcleblanc** [comment]
Thanks @cbetta 

For your requests:

- [x] ReadMe revisions: Done
- [x] Serverless: This current Skill won't have a Serverless component, and will work directly with AWS.
- [x] Screenshot: I added a new full screenshot to the ReadMe, feel free to edit - [available here](https://github.com/jcleblanc/sample-audio-skills/blob/master/voicebase-callcenter-audio-analysis/screenshots/skills_vb_full.png).

**Comment by cbetta** [comment]
@jcleblanc I think we decided on using Serverless for deploy instructions, in order to keep things simpler. Can you please bring the README in line with the other skills (pointing to the generic AWS instructions) and use the serverless CLI to deploy your skill?

**Comment by cbetta** [comment]
@jcleblanc can you please replace the screenshot with this?

chrome-frame

**Comment by eshaverma** [comment]
@cbetta  i think it's fine to show different deployment sample. It adds some variety in case people prefer differently

**Review by eshaverma — APPROVED** [review]

**Pull request merged**
